### PR TITLE
upgrade app to use hopr standard

### LINKED ISSUE #2: Upgrade to the HOPR standard
### Job Story

The HOPR tech team has recently introduced a [dApp standard](https://github.com/hoprnet/hoprnet/issues/3805).
In short, it's a minimum feature set we would like our featured dApps to support.
We would like you to upgrade `hopr-boomerang-chat` to support this feature set.

### Description

Upgrade [hopr-boomerang-chat](https://github.com/hoprnet/hopr-boomerang-chat) and ensure it supports all features of the [dApp standard](https://github.com/hoprnet/hoprnet/issues/3805).

This includes:

- consistent endpoint configuration
- use API v2 fully (currently uses WS API v1 instead of v2)
- README.md page needs to follow the standard

### Definition of Done

Once [hopr-boomerang-chat](https://github.com/hoprnet/hopr-boomerang-chat) follows the standard.

### Developing HOPR

- [running HOPR locally](https://docs.hoprnet.org/developers/starting-local-cluster#local-setup)

### What is HOPR?

Find out more about HOPR at the following links:

- [HOPR Website](https://hoprnet.org)
- [hoprnet monorepo](https://github.com/hoprnet/hoprnet)
- [hoprnet docs](http://docs.hoprnet.org)
- [discord](https://discord.com/invite/dEAWC4G)

### PR DESCRIPTION
**Pull request by boyin0x**
Closes #2
@nionis, please let me know if you need any help with other hopr standard bounties.

### CODE REVIEW

**Comment by nionis** [comment]
hey @boyin0x, could you also make sure if follows the README standard?

the README.md page must include
- introduction to dApp
- short technical explanation
- DEMO showcase (short video of it working)

**Comment by boyin0x** [comment]
hey @nionis , just updated the readme and uploaded the video as well.
Also added support for Gitpod.

**Comment by nionis** [comment]
Hey @boyin0x! Great work, paying out the bounty today.
Please take a look at similar bounties over at https://bounties.hoprnet.org/, example:
https://github.com/hoprnet/hopr-status-board/issues/3
https://github.com/hoprnet/myne-chat/issues/139 (taken but can be reassigned if assigned person doesn't reply)

**Comment by boyin0x** [comment]
Hi @nionis, thanks, yes sure, I re-applied in status-board but in myne-chat It says it's someone already assigned.

**Pull request merged**
